spring:
  application:
    name: itoken-web-admin
  boot:
    admin:
      client:
        url: http://192.168.161.140:8084
  zipkin:
    base-url: http://192.168.161.140:9411
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8601

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.161.140:8761/eureka/,http://192.168.161.140:8861/eureka/,http://192.168.161.140:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info