version: '3.1'
services:
  itoken-eureka:
    restart: always
    image: 192.168.161.136:5000/itoken-eureka
    container_name: itoken-eureka
    ports:
      - 8761:8761
    networks:
      - itoken_eureka
networks:
  itoken_eureka: